### ISSUE TITLE
Errors in DCMTK building at HPC Clusters

### ISSUE THREAD

**Issue by wuye4567** [pnlbwh/ukftractography#86] opened 2017-10-24 16:07 UTC
DCMTK building always erroring when compile UKFTractography (4a428a7) to HCP Clusters
**************************************
[log.txt](https://github.com/pnlbwh/ukftractography/files/1411556/log.txt)

**Comment by ihnorton** [comment] 2017-10-24 16:44
Thanks! Pretty sure the issue is DCMTK building in C++11 mode on an old compiler. I'll take a look.

**Comment by hjmjohnson** [comment] 2017-10-24 18:03
DCMTK needs a little special attention when building with C++11.  There is a CMake flag that needs to be set.

 

Hans

**Comment by ihnorton** [comment] 2017-10-27 20:00
@wuye4567 the code checkout in `/data/lmi/software/UKF/ukf_170228_421a7ad/ukftractography` is from Feb 28, 2017. These issues have already been fixed in current UKF source (by DCMTK updates etc.).

I ran a successful clean build on the same cluster, but I'm not going to update that directory because Fan might using it for projects (cc @zhangfanmark).

**Closed by ihnorton** 2017-10-27 20:00 UTC
